### ISSUE TITLE
[enhancement] Выравнивание

### ISSUE THREAD

**Issue by BlueCat300** [Taraflex/Anilibria-releases-unlocker#1]
Как насчёт сделать выравнивание по левому краю для текста внутри таблички?
Скрин сделан на Opera Mobile (Android). Расширение работает через Adguard.
![Screenshot_20200219_111402](https://user-images.githubusercontent.com/42893969/74814909-4d9a7280-5309-11ea-9dac-895220ab86a9.jpg)

**Comment by Taraflex** [comment]
На не заблоченных релизах тоже выравнивание по центру. Думаю не стоит что-то менять.
![image](https://user-images.githubusercontent.com/1707271/74815629-a6b6d600-530a-11ea-8617-18c3fb6c71c1.png)
Для стилизации лучше сделать отдельный юзерскрипт
```js
// ==UserScript==
// @name      anilibria style
// @namespace taraflex
// @version   0.1
// @author    taraflex.red@gmail.com
// @match     http://anilibria.tv/release/*
// @match     http://www.anilibria.tv/release/*
// @match     https://anilibria.tv/release/*
// @match     https://www.anilibria.tv/release/*
// @grant     GM_addStyle
// ==/UserScript==

GM_addStyle(`
td[id^="torrentTableInfo"]{
text-align: left;
padding-left: 6px;
}
`);
```
